### ISSUE TITLE
Preserve newlines & whitespace in preformatted text

### ISSUE THREAD

**Issue by boisgera** [ArthurClemens/mithril-template-converter#19]
The HTML code

    <pre><code>if (condition) {
        doThis();
    } else {
        doThat();
    }
    </code></pre>

for example is translated to

    m("pre", 
      m("code", 
        "if (condition) { doThis(); } else { doThat(); } "
      )
    )

and hence rendered as

    if (condition) { doThis(); } else { doThat(); } 

instead of

    if (condition) { 
        doThis(); 
    } else { 
        doThat(); 
    } 

Could the content of pre elements be translated without whitespace & newline removal ? At least in theory ? 
(Somehow related to #5.)

Cheers,

SB

**Comment by ArthurClemens** [comment]
Solved in 1.3.1
